generator:
  class: sfPropelBoostrapGenerator
  param:
    model_class:           Category
    theme:                 sfBootstrapTheme
    non_verbose_templates: true
    with_show:             false
    singular:              Category
    plural:                Categorys
    route_prefix:          category
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, title, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
